services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./env/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - poc-concurrency-testing-network
    ports:
      - "9090:9090"
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - poc-concurrency-testing-network
    ports:
      - 3000:3000
    env_file:
      - ./env/grafana.env
    volumes:
      - ./env/grafana:/etc/grafana/provisioning/
  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: my_awesome_password
    volumes:
      - ./env/postgres/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - poc-concurrency-testing-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
  maria:
    image: mariadb:latest
    hostname: maria
    container_name: maria
    environment:
      MARIADB_ROOT_PASSWORD: my_awesome_root_password
      MARIADB_DATABASE: my_database # This can be the same as in schema.sql or a different one
      MARIADB_USER: user
      MARIADB_PASSWORD: my_awesome_password
    ports:
      - "3306:3306"
    networks:
      - poc-concurrency-testing-network
    volumes:
      - ./env/mariadb/init-scripts/1_schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./env/mariadb/init-scripts/2_seed_data.sql:/docker-entrypoint-initdb.d/2_seed_data.sql
      # - ./env/mariadb/mariadb_data:/var/lib/mysql # Optional: for persistent data storage
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"] # Simple connectivity check
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s # Give the database time to initialize


  resource-vertx:
    image: resource-vertx
    container_name: resource-vertx
    hostname: resource-vertx
    build: ./resource-vertx
    ports:
      - "9080:8080"
    networks:
      - poc-concurrency-testing-network
    depends_on:
      - maria
    cpu_count: 1

  api-spring-boot-basic:
    image: api-spring-boot-basic
    container_name: api-spring-boot-basic
    hostname: api-spring-boot-basic
    build: ./api-spring-boot-basic
    ports:
      - "8081:8080"
    networks:
      - poc-concurrency-testing-network
    depends_on:
      - resource-vertx
      - postgres
    cpu_count: 1
    environment:
      - POSTGRESQL_URL=jdbc:postgresql://postgres:5432/mydatabase
      - POSTGRESQL_USER=myuser
      - POSTGRESQL_PWD=my_awesome_password
      - RESOURCE_URL=http://resource-vertx:8080 # note: the port is the internal container port not the externally exposed/mapped port

  api-spring-boot-basic-vt:
    image: api-spring-boot-basic-vt
    container_name: api-spring-boot-basic-vt
    hostname: api-spring-boot-basic-vt
    build: ./api-spring-boot-basic-vt
    ports:
      - "8082:8080"
    networks:
      - poc-concurrency-testing-network
    depends_on:
      - resource-vertx
      - postgres
    cpu_count: 1
    environment:
      - POSTGRESQL_URL=jdbc:postgresql://postgres:5432/mydatabase
      - POSTGRESQL_USER=myuser
      - POSTGRESQL_PWD=my_awesome_password
      - RESOURCE_URL=http://resource-vertx:8080 # note: the port is the internal container port not the externally exposed/mapped port

  api-spring-boot-async:
    image: api-spring-boot-async
    container_name: api-spring-boot-async
    hostname: api-spring-boot-async
    build: ./api-spring-boot-async
    ports:
      - "8083:8080"
    networks:
      - poc-concurrency-testing-network
    depends_on:
      - resource-vertx
      - postgres
    cpu_count: 1
    environment:
      - POSTGRESQL_URL=jdbc:postgresql://postgres:5432/mydatabase
      - POSTGRESQL_USER=myuser
      - POSTGRESQL_PWD=my_awesome_password
      - RESOURCE_URL=http://resource-vertx:8080 # note: the port is the internal container port not the externally exposed/mapped port

networks:
  poc-concurrency-testing-network:
    driver: bridge