-- create_schema.sql
CREATE USER myuser IDENTIFIED BY "my_awesome_password" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
GRANT CONNECT, RESOURCE, DBA TO myuser;
ALTER USER myuser DEFAULT ROLE DBA;

CREATE TABLE myuser.mytable (
    id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    pro VARCHAR(11) UNIQUE NOT NULL,
    secondhalf VARCHAR(6) NOT NULL
);