global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  # - job_name: 'prometheus'

  #   # Override the global default and scrape targets from this job every 5 seconds.
  #   scrape_interval: 5s

  #   static_configs:
      # - targets: ['localhost:9090']

  - job_name: 'resource-vertx'
    metrics_path: '/q/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: ['resource-vertx:8080']
        labels:
          application: 'resource-vertx'

  - job_name: 'api-spring-boot-basic'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['api-spring-boot-basic:8080']
        labels:
          application: 'api-spring-boot-basic'

  - job_name: 'api-spring-boot-basic-vt'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['api-spring-boot-basic-vt:8080']
        labels:
          application: 'api-spring-boot-basic-vt'

  - job_name: 'api-spring-boot-async'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['api-spring-boot-async:8080']
        labels:
          application: 'api-spring-boot-async'

  # - job_name: 'resource-quarkus'
  #   metrics_path: '/q/metrics'
  #   scrape_interval: 3s
  #   static_configs:
  #     - targets: ['resource-quarkus:9984']
  #       labels:
  #         application: 'resource-quarkus'



